default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  strict: false
  host: <%= ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV.fetch('MYSQL_PORT') %>
  username: <%= ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') %>

development:
  <<: *default
  host: <%= ENV['MYSQL_HOST_DEVELOPMENT'] || ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV['MYSQL_PORT_DEVELOPMENT'] || ENV.fetch('MYSQL_PORT') %>
  username: <%= ENV['MYSQL_USERNAME_DEVELOPMENT'] || ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV['MYSQL_PASSWORD_DEVELOPMENT'] || ENV.fetch('MYSQL_PASSWORD') %>
  database: <%= ENV['MYSQL_DATABASE_DEVELOPMENT'] || 'suikoden_election_2017_development' %>

production:
  <<: *default
  host: <%= ENV['MYSQL_HOST_PRODUCTION'] || ENV.fetch('MYSQL_HOST') %>
  port: <%= ENV['MYSQL_PORT_PRODUCTION'] || ENV.fetch('MYSQL_PORT') %>
  username: <%= ENV['MYSQL_USERNAME_PRODUCTION'] || ENV.fetch('MYSQL_USERNAME') %>
  password: <%= ENV['MYSQL_PASSWORD_PRODUCTION'] || ENV.fetch('MYSQL_PASSWORD') %>
  database: <%= ENV['MYSQL_DATABASE_PRODUCTION'] || 'suikoden_election_2017_production' %>

test:
  <<: *default
  host: <%= ENV['MYSQL_HOST_TEST'] || '127.0.0.1' %>
  port: <%= ENV['MYSQL_PORT_TEST'] || 3306 %>
  username: <%= ENV['MYSQL_USERNAME_TEST'] || 'gss2017' %>
  password: <%= ENV['MYSQL_PASSWORD_TEST'] || 'gss2017_pasword' %>
  database: <%= ENV['MYSQL_DATABASE_TEST'] || 'suikoden_election_2017_test' %>
