default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  <<: *default
  host: <%= ENV['PG_HOST_DEVELOPMENT'] || 'localhost' %>
  port: <%= ENV['PG_PORT_DEVELOPMENT'] || 5432 %>
  username: <%= ENV['PG_USERNAME_DEVELOPMENT'] || 'root' %>
  password: <%= ENV['PG_PASSWORD_DEVELOPMENT'] || 'password' %>
  database: gss2017_development
  template: template0
  collation: ja_JP.UTF-8
  ctype: ja_JP.UTF-8

production:
  <<: *default
  host: <%= ENV['PG_HOST_PRODUCTION'] || 'localhost' %>
  port: <%= ENV['PG_PORT_PRODUCTION'] || 5432 %>
  username: <%= ENV['PG_USERNAME_PRODUCTION'] || 'root' %>
  password: <%= ENV['PG_PASSWORD_PRODUCTION'] || 'password' %>
  database: gss2017_production
  template: template0
  collation: ja_JP.UTF-8
  ctype: ja_JP.UTF-8

test:
  <<: *default
  host: <%= ENV['PG_HOST_TEST'] || 'localhost' %>
  port: <%= ENV['PG_PORT_TEST'] || 5432 %>
  username: <%= ENV['PG_USERNAME_TEST'] || 'gss2017' %>
  password: <%= ENV['PG_PASSWORD_TEST'] || 'gss2017_password' %>
  database: gss2017_test
